@url=http://localhost:8080/api/answer

GET {{url}}

###

GET {{url}}/questionId/1

GET {{url}}/myAnswers
Authorization: 1

###

GET {{url}}/myAnswers


### No questions found for user

GET {{url}}/myAnswers
Authorization: 999

### 

# Happy Path
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: 1

{
  "body": "testAnswer",
  "questionId": 8
}

### 

# No Authorization Header 401
POST {{url}} HTTP/1.1
Content-Type: application/json

{
  "body": "This is a test question"
}

### fail user does not exist

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: 999

{
  "body": "This is a test question",
  "questionId": 3
}

### pass case

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: 1

 {
    "body": "This is a test question2",
    "questionId": 8
 }

### 


# No authorization header -> 401
PUT {{url}}/2 HTTP/1.1
Content-Type: application/json

  {
    "questionId": 2,
    "body": "This is a test question3"
 }

### 

# Not this panel's owner -> 403
PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: 2

{
    "questionId": 8,
    "body": "This is a test question2"
 }

###


# Question not found -> 400
PUT {{url}}/99 HTTP/1.1
Content-Type: application/json
Authorization: 1

{
    "questionId": 99,
    "body": "This is a test question2"
 }

###

// Update Unhappy Path - Missing Fields

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: 1

{
    "questionId": 8,
    "body": " "
 }

###


# Happy Path
DELETE {{url}}/2 HTTP/1.1
Authorization: 1

###

# No authorization header - > 401
DELETE {{url}}/2 HTTP/1.1

###


# Not the owner of the question - > 403
DELETE {{url}}/1 HTTP/1.1
Authorization: 2

###