services:
  my-service:
    image: nginx:1.21-alpine
    container_name: nginx1
    hostname: nginx1
    pull_policy: never
    restart: "no"
    command: /bin/sh
    ports:
      - 8080:80
    environment:
      - KEY="the value"